"""added age field

Revision ID: 5a846253ab5a
Revises: c30c19bf2437
Create Date: 2026-10-03 16:40:32.076372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a846253ab5a'
down_revision: Union[str, Sequence[str], None] = 'c30c19bf2437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('persons', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('name', sa.INTEGER(), nullable=True))
    op.drop_column('persons', 'age')
    op.drop_column('persons', 'first_name')
    # ### end Alembic commands ###
